### ISSUE TITLE
无法获取同步微信通讯录好友

### ISSUE THREAD

**Issue by Woxiee** [BeForerver/RedEnvelope#1]
您好,我在运行您的项目时,真机测试无法同步微信好友

**Comment by Be-Forever** [comment]
是不是微信版本没有兼容的原因 部分click的定位是根据代码中元素id进行定位的 不同的微信版本id不一样

**Comment by Woxiee** [comment]
<img width="654" alt="image" src="https://user-images.githubusercontent.com/15901666/159665144-43f73867-1783-4dd7-85f9-49e2cf69b741.png">
我替换成微信最新的版本, 然后点击"初始化好友列表",任然获取不到好友列表,能帮忙测试下吗

**Comment by Be-Forever** [comment]
需要同时替换元素id的值 这需要反编译你所需的微信版本进行分析 只替换版本号是不行的

**Comment by Be-Forever** [comment]
或者利用ui检测工具查看元素id
